name: Test String Type (No Validation)
on:
  workflow_dispatch:
    inputs:
      upgrade_type:
        description: 'Type of upgrade'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Upgrade type input value: ${{ inputs.upgrade_type }}"
          echo "Done"
